### PR TITLE
Adding fish functionality

### PR DESCRIPTION
**Pull request by endowdly**
I wrote a fish port of `up.sh` .

I tested it a little in basic cases and it seems to function exactly like `up`. 

Included `up.fish` and updated the `README` to reflect the addition.

### CODE REVIEW

**Comment by shannonmoeller** [comment]
Hey, this is awesome! Thanks for the PR. I'll give it a review, kick the tires, and see about a merge.

**Comment by endowdly** [comment]
Sure thing! If you find a wobble let me know, and I'll see if I can fix it. 

...also that comment about recursion isn't snarky. I just never think to do it, so when I see it I'm always impressed! :)

**Comment by shannonmoeller** [comment]
I didn't take it as snark. Genuine amusement here. :)

**Comment by shannonmoeller** [comment]
Code looks great. Just going to give it a test drive.

**Comment by shannonmoeller** [comment]
All of the `up` execution works as expected (nice work on the port), but when I try to use `<TAB>` completion, fish lists the current directory's contents instead of parent dirs.

Actual:

```
smoeller@laptop ~/R/g/s/up> up<TAB>
README.md  up.fish  up.sh
```

Expected:

```
smoeller@laptop ~/R/g/s/up> up<TAB>
Repos/  Users/  github/  home/  shannonmoeller/  smoeller/
```

I _think_ line 82 should be as follows, but I'm not fluent in fish:

```
complete -c up -f _up
```

**Comment by endowdly** [comment]
Yeah, I suspect you're right. I'll take a look!

**Comment by shannonmoeller** [comment]
Possibly helpful? https://github.com/fish-shell/fish-shell/blob/master/share/completions/grunt.fish#L17

**Comment by endowdly** [comment]
I got it, I think to get the parent directory, line 82 should read
```
complete -c up -a "(cd ..)" 
``` 
as per [fish complete](https://fishshell.com/docs/current/commands.html#complete)

I'm pushing now :)

**Comment by endowdly** [comment]
Ooo wait, this causes unintended behavior on multiple completions. Needs to be `ls ..`

**Comment by shannonmoeller** [comment]
Perhaps: `complete -c up -fa '(_up)'` ?

**Comment by endowdly** [comment]
Hm, `compgen` isn't included in fish, which favors it's own `complete`. I'll have to rework `_up` into the `complete` call somehow.

**Comment by shannonmoeller** [comment]
Would something as simple as this work?

```fish
function _up
  string trim --chars=/ (dirname $PWD) | string split /
end

complete -c up -fa '(_up)'
```

**[Edited]**

**Comment by endowdly** [comment]
I think I finally got it, with your help of course. 

```sh
function _up
  set --local p ( string split / $PWD)

  for d in $p
    echo $d
  end
end

complete -c up -fa '(_up)'
```

phew!

**Comment by endowdly** [comment]
Hm, your edit is more 'safe'. Plus, I need to add `_up` with `funcsave` :)

**Comment by shannonmoeller** [comment]
Awesome work! Thanks again.

**Pull request merged**
